### ISSUE TITLE
Error: could not find function "PREPARE.MODEL.DATA"

### ISSUE THREAD

**Issue by Zoltrix** [jimthompson5802/kaggle-BNP-Paribas#3]
When i try to run the script to create Level 1 features i get this error. 

```
Error in do.ply(i) :
  task 1 failed - "could not find function "PREPARE.MODEL.DATA""
Calls: system.time -> llply -> <Anonymous> -> <Anonymous>
```

Here's the command i used
`Rscript src\L0_gbm21\create_level1_features.R`. 

Running on Windows

**Comment by jimthompson5802** [comment]
Sorry for not responding sooner.

All the code assumes the current working directory is the top level directory containing all the sub-directories.  I enforce this by defining an RStudio project.  Thus when I open the project, the working directory is automatically set to the proper location.

if you run getwd(), what does it say?

One more thing to check...in the module you cited, there is this R code:
`# import model configuration parameters`
`source(paste0(WORK.DIR,"/model_parameters.R"))`

What happens when the `source()` function executes?  The definition for PREPARE_MODEL_DATA is contained in `model_parameters.R`.

**Comment by jimthompson5802** [comment]
No further information provided.
